### PR TITLE
added package.json changes added Script changes

### PR DESCRIPTION
**Pull request by Ayushpanditmoto**
Added .env file
Added nodemon 
Added Script now both server can run concurrently

### CODE REVIEW

**Review by knight-95 — COMMENTED** [review]
Was it connecting with mongoDB Database ?

**Comment by Ayushpanditmoto** [comment]
You have change .env.example file to .env and add mongodb link

**Comment by Ayushpanditmoto** [comment]
I can't access your mongodb link because of restriction of ip address

**Comment by Ayushpanditmoto** [comment]
but yes its connected to mongo db

**Comment by Ayushpanditmoto** [comment]
Screenshot_14

**Comment by Ayushpanditmoto** [comment]
okay i have made changes to script you can run this in your local computer
and please accept my pr request

**Comment by Ayushpanditmoto** [comment]
Can you marked this as hactoberfest accepted

**Comment by Ayushpanditmoto** [comment]
Otherwise its would not be count

**Comment by knight-95** [comment]
The app is broken after the second commit 
Let me check and get back to you

**Comment by knight-95** [comment]
> Otherwise its would not be count

It will be counted, be assured

**Pull request merged**
